version: "3"
services:
 ms-sql-server:
  image: mcr.microsoft.com/mssql/server:2022-latest
  environment:
   ACCEPT_EULA: "Y"
   SA_PASSWORD: "Pa55w0rd2022"
   MSSQL_PID: Express
  ports:
   - "1433:1433"
 forest-web-site:
  build: .
  ports:
   - "8080:80"